version: '3.4'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  httpbin:
    build:
      context: ./src/ResiliencePatterns.Core.Httpbin/
    ports:
      - 9000:80

  vaurien:
    build:
      context: ./src/ResiliencePatterns.Core.Vaurien/
    volumes:
      - ./src/ResiliencePatterns.Core.Vaurien/assets/etc/:/etc/
    ports:
      - 9001:80
    depends_on:
      - httpbin

  ResiliencePatternsDotNetApi:
    image: ${DOCKER_REGISTRY-}resiliencepatternsdotnetapi
    build:
      context: .
      dockerfile: src/ResiliencePatterns.DotNet.Api/Dockerfile
    ports:
      - 5001:80
    depends_on: 
      - vaurien
      - httpbin

  ResiliencePatternsJavaApi:
    image: ${DOCKER_REGISTRY-}resiliencepatternsjavaapi
    build:
      context: ./src/ResiliencePatterns.Java.Api/
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    depends_on:
      - vaurien
      - httpbin