version: '3.4'

services:
  httpbin:
    build: 
      context: ./src/ResiliencePatterns.Core.Httpbin/
    ports:
      - 9000:80

  vaurien:
    build: 
      context: ./src/ResiliencePatterns.Core.Vaurien/
    ports:
      - 9001:80
    depends_on: 
      - httpbin

  ResiliencePatterns.DotNet.api:
    image: ${DOCKER_REGISTRY-}resiliencepatternsdotnetapi
    build:
      context: .
      dockerfile: src/ResiliencePatterns.DotNet.Api/Dockerfile
    ports:
      - 5001:80
    depends_on: 
      - vaurien
      - httpbin