resilience4j.circuitbreaker:
  instances:
    circuit_breaker_A:
      failureRateThreshold: 50
      slidingWindowSize: 5
      minimumNumberOfCalls: 1
      waitDurantionInOpenState: 30000
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 1000

resilience4j.retry:
  instances:
    backendA:
      maxRetryAttempts: 5
      waitDuration: 1s


service:
  url: http://httpbin.org/status/200

url:
  success: http://httpbin.org/status/200
  error: http://httpbin.org/status/500
  delay: http://localhost/delay/5

options:
  errorRate: 100
  requestCount: 50
  concurrentClients: 2

management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true